### ISSUE TITLE
Database file

### ISSUE THREAD

**Issue by mfz97** [nhasoenhasan/PHP-Naive-Bayes-expert-system-for-the-diagnosis-of-mental-illnesses#1]
Hi, may I have the sql database file? Thank you.
fikrizahirulhaq97@gmail.com

**Comment by nhasoenhasan** [comment]
text me nur.hasan.job@gmail.com

**Comment by Ahtisham1231** [comment]
HI, 
Brother i am working on Lungs cancer prediction system but i am not getting how to do your project use naive byes algorithm it may help me please send database file. I send a message on gmail please send mysql file there
